export const ACTIONS = {
  FETCH_DATA_LOADING: 'FETCH_DATA_LOADING',
  FETCH_EXERCISES_SUCCESS: 'FETCH_EXERCISES_SUCCESS',
  FETCH_EXERCISES_FAILURE: 'FETCH_EXERCISES_FAILURE',
  FETCH_FOOD_SUCCESS: 'FETCH_FOOD_SUCCESS',
  FETCH_FOOD_FAILURE: 'FETCH_FOOD_FAILURE',
  FETCH_GOALS_SUCCESS: 'FETCH_GOALS_SUCCESS',
  FETCH_GOALS_FAILURE: 'FETCH_GOALS_FAILURE'
};
